# baseURL: http://blog.haktec.de/
baseURL: http://192.168.1.103:1313/
title: My Blog
uglyurls: false
disablePathToLower: true
languageCode: en-US
canonifyURLs: false
# pygmentsStyle: "monokai"
pygmentsCodefences: true
pygmentsUseClasses: true
MetaDataFormat: yaml

taxonomies:
  tag: tags
  category: categories

related:
  threshold: 50
  includeNewer: true
  toLower: true
  indices:
  - name: tags
    weight: 100
  - name: keywords
    weight: 50
  - name: date
    weight: 10

author: Hannes Körber
params:
  description: "Blog description"
  author: Hannes Körber
  social:
    - name: github
      link: https://github.com/hakoerber
      icon: fa-github
      style: fab
    - name: gitlab
      link: https://gitlab.com/whatevsz
      icon: fa-gitlab
      style: fab
    - name: linkedin
      link: https://www.linkedin.com/in/hannes-k%C3%B6rber-479ab5122
      icon: fa-linkedin
      style: fab
    - name: xing
      link: https://www.xing.com/profile/Hannes_Koerber
      icon: fa-xing
      style: fab
    - name: keybase
      link: https://keybase.io/hakoerber
      icon: fa-key
      style: fas
    # - name: twitter
    #   link: https://twitter.com/whatevsz
    #   icon: fa-twitter
    #   style: fab
    - name: E-Mail
      link: mailto:hannes.koerber@gmail.com
      icon: fa-envelope
      style: fas
      description: Send me a mail!
    - name: RSS
      link: /blog/index.xml
      icon: fa-rss
      style: fas
      description: Follow my blog on RSS!


permalinks:
  blog: /:section/:year/:month/:day/:title/

menu:
  main:
    - name: "Blog"
      weight: 1
      url : "/blog/"

    - name: "Projects"
      weight: 2
      url : "/projects/"

    - name: "Work"
      weight: 4
      url : "/work/"
